### ISSUE TITLE
Tailwind 3 error

### ISSUE THREAD

**Issue by roman3000** [kenhyuwa/litepie-datepicker#72]
Hi, I noticed this project has been update to work with tailwind 3 so I tried to install it but I am getting an error

Found: tailwindcss@3.1.3
npm ERR! node_modules/tailwindcss
npm ERR!   dev tailwindcss@"^3.0.24" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer tailwindcss@"^2.0.3" from litepie-datepicker@1.0.14
npm ERR! node_modules/litepie-datepicker
npm ERR!   litepie-datepicker@"*" from the root project

Any suggestions on how to fix this? Thanks

**Comment by HeartwinJ** [comment]
It is because although it has been updated here, it hasn't been published to the NPM Registry.
You have to wait until it is published to use this with Tailwind 3. Meanwhile you can use this package: https://www.npmjs.com/package/litepie-datepicker-tw3 as suggested in #53 

@kenhyuwa , Please publish to npmjs.

**Comment by roman3000** [comment]
Hi, thanks for the reply. Hopefully the NPM registry gets updated soon.
